version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Mapeando a porta 80 do contêiner para a porta 4200 do host
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: minhasenha
      MYSQL_DATABASE: gerencia.ai
    volumes:
      - ./mysql/conf.cnf:/etc/mysql/conf.d/conf.cnf

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      - angular-app
